server:
  port: 3000
  base-url: /gitvillance
db:
  description: base de prueba
  host: localhost
  port: 5432
  database: gitvillance_db
  schema: gitvillance
  user: gitvillance_admin
  password: cambiar_esta_clave
install:
  dump:
    db:
      owner: gitvillance_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true