name: build-and-test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  call-workflow:
    uses: codenautas/.github/.github/workflows/node-build-and-test.yaml@v0
