name: build-and-test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    uses: codenautas/node-build-and-test-action@v0
    secrets: inherit